#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
from PyQt5.QtWidgets import QApplication
from app_code.ptvideogui import PtVideoGui, PtVideoGuiMain


if __name__ == '__main__':

    app = QApplication(sys.argv)

    ex = PtVideoGuiMain()

    sys.exit(app.exec_())
